version: '3'

services:
  plex-monitor:
    build: .
    image: plex-monitor:latest
    container_name: plex-monitor
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=America/New_York  # Set your timezone here
    network_mode: bridge
